In [1]:
import pandas as pd
import os
import numpy as np

In [2]:
working_directory = os.getcwd()
print(working_directory)

d:\GitHub\TDM-INP-College-Enrollment

In [3]:
# Read 2020 csv as pandas dataframe object
data_folder = os.path.join(r"data\USHE 2025 Enrollment")
int_folder = os.path.join(r"intermediate")

df_enroll = pd.read_excel(
    os.path.join(data_folder, "WFRC Data Request_Final.xlsx"),
    sheet_name="Sheet1",
    usecols="A:G",  # Selects columns A through G
    nrows=6014,  # Reads 6014 rows (A1 is header, then 6014 rows of data)
)

df_enroll

,Institution,Site,Academic Year,Term,ZIPCODE,Full_or_Part_Time,Headcount
0,Salt Lake Community College,Main Campus,2025,2,84003,Full-Time,38
1,Salt Lake Community College,Main Campus,2025,2,84003,Part-Time,70
2,Salt Lake Community College,Main Campus,2025,2,84004,Full-Time,12
3,Salt Lake Community College,Main Campus,2025,2,84004,Part-Time,13
4,Salt Lake Community College,Main Campus,2025,2,84005,Full-Time,51
...,...,...,...,...,...,...,...
6009,Weber State University,Course taught from an out of state site,2025,2,84660,Full-Time,1
6010,Weber State University,Course taught from an out of state site,2025,2,84667,Full-Time,1
6011,Weber State University,Course taught from an out of state site,2025,2,84713,Full-Time,1
6012,Weber State University,Course taught from an out of state site,2025,2,84737,Full-Time,1
6013,Weber State University,Course taught from an out of state site,2025,2,84790,Full-Time,1

In [11]:
df_enroll.value_counts(["Institution", "Site"]).sort_index().reset_index(name="Total")

                    Institution                                               Site  Total
0   Salt Lake Community College            Correctional Facility--West Valley City      6
1   Salt Lake Community College  Course is taught at Other site, not Owned or L...    148
2   Salt Lake Community College                                        Main Campus    284
3   Salt Lake Community College                              SLCC - Airport Center     62
4   Salt Lake Community College                               SLCC - Jordan Campus    192
5   Salt Lake Community College                      SLCC - Larry H. Miller Campus    102
6   Salt Lake Community College                           SLCC - South City Center    167
7   Salt Lake Community College                           SLCC - West Point Center     93
8   Salt Lake Community College                            SLCC - West Valley City     27
9   Salt Lake Community College        SLCC-UU Juniper building at Herriman Campus    103
10           University Of Utah  Course is taught at Other site, not Owned or L...    303
11           University Of Utah          Course taught from an out of country site     41
12           University Of Utah               Course taught from other leased site     29
13           University Of Utah                                        Main Campus    333
14           University Of Utah        SLCC-UU Juniper building at Herriman Campus     30
15           University Of Utah                                  UU - Sandy Center    140
16           University Of Utah                             UU - St. George Center     17
17        Utah State University  Course is taught at Other site, not Owned or L...    245
18        Utah State University  Course taught from Public Education Site (i.e....      7
19        Utah State University          Course taught from an out of country site      3
20        Utah State University               Course taught from other leased site     63
21        Utah State University                Course taught from other owned site     37
22        Utah State University                                        Main Campus    341
23        Utah State University             Technical College Campus--Uintah Basin     10
24        Utah State University        This portion of the course is taught online    415
25        Utah State University                              USU - Blanding Center     24
26        Utah State University                               USU - Brigham Center    104
27        Utah State University                                 USU - Delta Center      2
28        Utah State University                                  USU - Moab Center      5
29        Utah State University                                 USU - Ogden Center     74
30        Utah State University                                  USU - Orem Center     19
31        Utah State University                             USU - Roosevelt Center     18
32        Utah State University                             USU - Salt Lake Center     70
33        Utah State University                                USU - Tooele Center     37
34        Utah State University                             USU - Tremonton Center      4
35        Utah State University                                USU - Vernal Center     20
36        Utah State University                                       USUE - Price    137
37        Utah State University                         USUE - Workforce Education    139
38       Utah Valley University  Course is taught at Other site, not Owned or L...    154
39       Utah Valley University  Course taught from Public Education Site (i.e....     42
40       Utah Valley University               Course taught from other leased site     90
41       Utah Valley University                Course taught from other owned site    117
42       Utah Valley University                                        Main Campus    340
43       Utah Valley University        This portion of the course is taught online    352
44       Utah Valley University                            UVU - Heber City Center     25
45       Weber State University  Course is taught at Other site, not Owned or L...     54
46       Weber State University            Course taught from an out of state site     23
47       Weber State University               Course taught from other leased site      7
48       Weber State University                Course taught from other owned site     11
49       Weber State University                                        Main Campus    301
50       Weber State University              Technical College Campus--Bridgerland     21
51       Weber State University                    Technical College Campus--Davis     42
52       Weber State University              Technical College Campus--Ogden-Weber     29
53       Weber State University        This portion of the course is taught online    318
54       Weber State University                            University Center--SLCC      4
55       Weber State University                                 WSU - Davis Center    179
56       Weber State University                           WSU - Farmington Station     54

In [12]:
dfCampusCodes = pd.DataFrame(
    [
        ["Salt Lake Community College", "Main Campus", "SLCC_MAIN"],
        ["Salt Lake Community College", "SLCC - Airport Center", "SLCC_AP"],
        ["Salt Lake Community College", "SLCC - Jordan Campus", "SLCC_JD"],
        ["Salt Lake Community College", "SLCC - Larry H. Miller Campus", "SLCC_ML"],
        ["Salt Lake Community College", "SLCC - South City Center", "SLCC_SC"],
        ["Salt Lake Community College", "SLCC - West Point Center", "SLCC_WC"],
        [
            "Salt Lake Community College",
            "SLCC-UU Juniper building at Herriman Campus",
            "SLCC_UH",
        ],
        ["University Of Utah", "Main Campus", "UOFU_MAIN"],
        [
            "University Of Utah",
            "SLCC-UU Juniper building at Herriman Campus",
            "UOFU_UH",
        ],
        ["University Of Utah", "UU - Sandy Center", "UOFU_SC"],
        ["University Of Utah", "UU - St. George Center", "UOFU_SG"],
        ["Utah State University", "Main Campus", "USU_MAIN"],
        ["Utah State University", "USU - Blanding Center", "USU_BD"],
        ["Utah State University", "USU - Brigham Center", "USU_BC"],
        ["Utah State University", "USU - Delta Center", "USU_DC"],
        ["Utah State University", "USU - Moab Center", "USU_MC"],
        ["Utah State University", "USU - Ogden Center", "USU_OG"],
        ["Utah State University", "USU - Orem Center", "USU_OR"],
        ["Utah State University", "USU - Roosevelt Center", "USU_RC"],
        ["Utah State University", "USU - Salt Lake Center", "USU_SL"],
        ["Utah State University", "USU - Tooele Center", "USU_TO"],
        ["Utah State University", "USU - Tremonton Center", "USU_TR"],
        ["Utah State University", "USU - VernalCenter", "USU_VC"],
        ["Utah State University", "USU - Price Center", "USU_PC"],
        ["Utah Valley University", "Main Campus", "UVU_MAIN"],
        ["Utah Valley University", "UVU - Heber City Center", "UVU_HC"],
        ["Weber State University", "Main Campus", "WSU_MAIN"],
        ["Weber State University", "Technical College Campus--Bridgerland", "WSU_TCCB"],
        ["Weber State University", "Technical College Campus--Davis", "WSU_TCCD"],
        [
            "Weber State University",
            "Technical College Campus--Ogden-Weber",
            "WSU_TCCOW",
        ],
        ["Weber State University", "University Center--SLCC", "WSU_UCSLC"],
        ["Weber State University", "WSU - Davis Center", "WSU_DAVIS"],
        ["Weber State University", "WSU - Farmington Station", "WSU_FS"],
    ],
    columns=["Institution", "Site", "COLLEGE"],
)

dfCampusCodes

                    Institution                                         Site    COLLEGE
0   Salt Lake Community College                                  Main Campus  SLCC_MAIN
1   Salt Lake Community College                        SLCC - Airport Center    SLCC_AP
2   Salt Lake Community College                         SLCC - Jordan Campus    SLCC_JD
3   Salt Lake Community College                SLCC - Larry H. Miller Campus    SLCC_ML
4   Salt Lake Community College                     SLCC - South City Center    SLCC_SC
5   Salt Lake Community College                     SLCC - West Point Center    SLCC_WC
6   Salt Lake Community College  SLCC-UU Juniper building at Herriman Campus    SLCC_UH
7            University Of Utah                                  Main Campus  UOFU_MAIN
8            University Of Utah  SLCC-UU Juniper building at Herriman Campus    UOFU_UH
9            University Of Utah                            UU - Sandy Center    UOFU_SC
10           University Of Utah                       UU - St. George Center    UOFU_SG
11        Utah State University                                  Main Campus   USU_MAIN
12        Utah State University                        USU - Blanding Center     USU_BD
13        Utah State University                         USU - Brigham Center     USU_BC
14        Utah State University                           USU - Delta Center     USU_DC
15        Utah State University                            USU - Moab Center     USU_MC
16        Utah State University                           USU - Ogden Center     USU_OG
17        Utah State University                            USU - Orem Center     USU_OR
18        Utah State University                       USU - Roosevelt Center     USU_RC
19        Utah State University                       USU - Salt Lake Center     USU_SL
20        Utah State University                          USU - Tooele Center     USU_TO
21        Utah State University                       USU - Tremonton Center     USU_TR
22        Utah State University                           USU - VernalCenter     USU_VC
23        Utah State University                           USU - Price Center     USU_PC
24       Utah Valley University                                  Main Campus   UVU_MAIN
25       Utah Valley University                      UVU - Heber City Center     UVU_HC
26       Weber State University                                  Main Campus   WSU_MAIN
27       Weber State University        Technical College Campus--Bridgerland   WSU_TCCB
28       Weber State University              Technical College Campus--Davis   WSU_TCCD
29       Weber State University        Technical College Campus--Ogden-Weber  WSU_TCCOW
30       Weber State University                      University Center--SLCC  WSU_UCSLC
31       Weber State University                           WSU - Davis Center  WSU_DAVIS
32       Weber State University                     WSU - Farmington Station     WSU_FS

In [18]:
df_enroll.groupby("Institution").agg({"Headcount": ["size", "sum"]})

                            Headcount
                                 size    sum
Institution
Salt Lake Community College      1184  23802
University Of Utah                893  44633
Utah State University            1774  32782
Utah Valley University           1120  41257
Weber State University           1043  24442

In [19]:
df_enroll.groupby(["Institution", "Site"]).agg({"Headcount": ["size", "sum"]})

                                                                               Headcount  \
                                                                                    size
Institution                 Site
Salt Lake Community College Correctional Facility--West Valley City                    6
                            Course is taught at Other site, not Owned or Le...       148
                            Main Campus                                              284
                            SLCC - Airport Center                                     62
                            SLCC - Jordan Campus                                     192
                            SLCC - Larry H. Miller Campus                            102
                            SLCC - South City Center                                 167
                            SLCC - West Point Center                                  93
                            SLCC - West Valley City                                   27
                            SLCC-UU Juniper building at Herriman Campus              103
University Of Utah          Course is taught at Other site, not Owned or Le...       303
                            Course taught from an out of country site                 41
                            Course taught from other leased site                      29
                            Main Campus                                              333
                            SLCC-UU Juniper building at Herriman Campus               30
                            UU - Sandy Center                                        140
                            UU - St. George Center                                    17
Utah State University       Course is taught at Other site, not Owned or Le...       245
                            Course taught from Public Education Site (i.e. ...         7
                            Course taught from an out of country site                  3
                            Course taught from other leased site                      63
                            Course taught from other owned site                       37
                            Main Campus                                              341
                            Technical College Campus--Uintah Basin                    10
                            This portion of the course is taught online              415
                            USU - Blanding Center                                     24
                            USU - Brigham Center                                     104
                            USU - Delta Center                                         2
                            USU - Moab Center                                          5
                            USU - Ogden Center                                        74
                            USU - Orem Center                                         19
                            USU - Roosevelt Center                                    18
                            USU - Salt Lake Center                                    70
                            USU - Tooele Center                                       37
                            USU - Tremonton Center                                     4
                            USU - Vernal Center                                       20
                            USUE - Price                                             137
                            USUE - Workforce Education                               139
Utah Valley University      Course is taught at Other site, not Owned or Le...       154
                            Course taught from Public Education Site (i.e. ...        42
                            Course taught from other leased site                      90
                            Course taught from other owned site                      117
                            Main Campus                                              340
                            This portion of the course is taught online              352
                            UVU - Heber City Center                                   25
Weber State University      Course is taught at Other site, not Owned or Le...        54
                            Course taught from an out of state site                   23
                            Course taught from other leased site                       7
                            Course taught from other owned site                       11
                            Main Campus                                              301
                            Technical College Campus--Bridgerland                     21
                            Technical College Campus--Davis                           42
                            Technical College Campus--Ogden-Weber                     29
                            This portion of the course is taught online              318
                            University Center--SLCC                                    4
                            WSU - Davis Center                                       179
                            WSU - Farmington Station                                  54


                                                                                  sum
Institution                 Site
Salt Lake Community College Correctional Facility--West Valley City               239
                            Course is taught at Other site, not Owned or Le...    783
                            Main Campus                                         15618
                            SLCC - Airport Center                                 101
                            SLCC - Jordan Campus                                 3045
                            SLCC - Larry H. Miller Campus                         369
                            SLCC - South City Center                             2323
                            SLCC - West Point Center                              333
                            SLCC - West Valley City                               130
                            SLCC-UU Juniper building at Herriman Campus           861
University Of Utah          Course is taught at Other site, not Owned or Le...  16011
                            Course taught from an out of country site              73
                            Course taught from other leased site                   37
                            Main Campus                                         27488
                            SLCC-UU Juniper building at Herriman Campus            45
                            UU - Sandy Center                                     902
                            UU - St. George Center                                 77
Utah State University       Course is taught at Other site, not Owned or Le...   2188
                            Course taught from Public Education Site (i.e. ...     10
                            Course taught from an out of country site             939
                            Course taught from other leased site                  119
                            Course taught from other owned site                    61
                            Main Campus                                         13684
                            Technical College Campus--Uintah Basin                 29
                            This portion of the course is taught online         13141
                            USU - Blanding Center                                 194
                            USU - Brigham Center                                  360
                            USU - Delta Center                                      2
                            USU - Moab Center                                      48
                            USU - Ogden Center                                    149
                            USU - Orem Center                                      22
                            USU - Roosevelt Center                                 73
                            USU - Salt Lake Center                                 98
                            USU - Tooele Center                                   134
                            USU - Tremonton Center                                  6
                            USU - Vernal Center                                   169
                            USUE - Price                                          766
                            USUE - Workforce Education                            590
Utah Valley University      Course is taught at Other site, not Owned or Le...    790
                            Course taught from Public Education Site (i.e. ...     78
                            Course taught from other leased site                  308
                            Course taught from other owned site                   525
                            Main Campus                                         21467
                            This portion of the course is taught online         18046
                            UVU - Heber City Center                                43
Weber State University      Course is taught at Other site, not Owned or Le...    172
                            Course taught from an out of state site                25
                            Course taught from other leased site                    8
                            Course taught from other owned site                    11
                            Main Campus                                         10366
                            Technical College Campus--Bridgerland                  61
                            Technical College Campus--Davis                        96
                            Technical College Campus--Ogden-Weber                  62
                            This portion of the course is taught online         11386
                            University Center--SLCC                                 4
                            WSU - Davis Center                                   2080
                            WSU - Farmington Station                              171

In [20]:
# Use strings "size" and "sum" instead of np.size and np.sum
df_enroll.groupby(["Institution", "Site"]).agg({"Headcount": ["size", "sum"]}).sum()

Headcount  size      6014
           sum     166916
dtype: int64

In [22]:
df_enroll[
    (df_enroll["Institution"] == "University Of Utah")
    & (df_enroll["Site"] == "Main Campus")
].groupby(["Institution", "Site", "ZIPCODE"]).agg({"Headcount": ["size", "sum"]})

                                       Headcount
                                            size  sum
Institution        Site        ZIPCODE
University Of Utah Main Campus 84003           2  276
                               84004           2   70
                               84005           2  128
                               84006           1    1
                               84009           2  408
...                                          ...  ...
                               84779           1    1
                               84780           2   46
                               84783           1    2
                               84790           2  103
                               84901           1    1

[209 rows x 2 columns]

In [23]:
dfTotEnrolByZip = df_enroll.groupby(
    ["Institution", "Site", "ZIPCODE"], as_index=False
).agg(TotEnrol=("Headcount", "sum"))
dfTotEnrolByZip.to_csv(
    os.path.join(int_folder, "campus_totenrol_byzip.csv"), index=False
)
dfTotEnrolByZip

,Institution,Site,ZIPCODE,TotEnrol
0,Salt Lake Community College,Correctional Facility--West Valley City,84116,198
1,Salt Lake Community College,Correctional Facility--West Valley City,84121,1
2,Salt Lake Community College,Correctional Facility--West Valley City,84130,1
3,Salt Lake Community College,Correctional Facility--West Valley City,84634,39
4,Salt Lake Community College,"Course is taught at Other site, not Owned or L...",84003,3
...,...,...,...,...
3953,Weber State University,WSU - Farmington Station,84404,3
3954,Weber State University,WSU - Farmington Station,84405,7
3955,Weber State University,WSU - Farmington Station,84414,7
3956,Weber State University,WSU - Farmington Station,84501,1
3957,Weber State University,WSU - Farmington Station,84601,1

In [24]:
dfTotEnrolByZip_College = pd.DataFrame.merge(
    dfCampusCodes, dfTotEnrolByZip, on=["Institution", "Site"]
)
dfTotEnrolByZip_College = dfTotEnrolByZip_College.drop(
    columns=(["Institution", "Site"])
)
dfTotEnrolByZip_College

        COLLEGE  ZIPCODE  TotEnrol
0     SLCC_MAIN    84003       108
1     SLCC_MAIN    84004        25
2     SLCC_MAIN    84005       160
3     SLCC_MAIN    84006         5
4     SLCC_MAIN    84009       487
...         ...      ...       ...
2072     WSU_FS    84404         3
2073     WSU_FS    84405         7
2074     WSU_FS    84414         7
2075     WSU_FS    84501         1
2076     WSU_FS    84601         1

[2077 rows x 3 columns]

In [25]:
dfTotEnrolByZip_College.to_csv(
    os.path.join(int_folder, "TotEnrolByZipByCollege.csv"), index=False
)